name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hardhat-tests:
    name: Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run tests
        run: |
          npx hardhat test

  foundry-tests:
    name: Foundry Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install OpenZeppelin Contracts
        run: |
          cd audit
          forge install OpenZeppelin/openzeppelin-contracts
      - name: Copy contract to Foundry src
        run: |
          mkdir -p audit/src
          cp contracts/ArtifexToken.sol audit/src/
      - name: Run Foundry tests
        run: |
          cd audit
          forge test -vv 